### PR TITLE
Add Haproxy frontend Maxcon

### PR DESCRIPTION
**Pull request by HectorRos**
Fix the problem with maxcon:http://i.imgur.com/5VeZFqq.png
Answer: http://stackoverflow.com/a/4824262

Result: http://i.imgur.com/OYVyCJf.png

(Based on my MaxConn environment variable).

Thanks !

### CODE REVIEW

**Comment by Dids** [comment]
+1. Hope this gets integrated soon.

**Comment by tifayuki** [comment]
Your fix only add the maxconn to the default_frontend, which means for those who use VIRTUAL_HOST, they need to use `EXTRA_SETTINGS` to specify maxconn to make it work. Right?

**Comment by HectorRos** [comment]
Yes @tifayuki ! This only work with default_frontend, if you add Virtual Hosts, you need to add the value with EXTRA_SETTINGS, but if you use default_frontend you can't add it, with the little change, it is fixed.

**Comment by tifayuki** [comment]
Cool, merged
Thank you

**Pull request merged**
