### PR TITLE
Support Proxy Protocol

### PR DESCRIPTION
**Pull request by nclaw**
Enable `accept-proxy` as per [haproxy-aws](https://github.com/jvehent/haproxy-aws)

### CODE REVIEW

**Comment by tifayuki** [comment]
This can be done by setting `EXTRA_BIND_SETTINGS=443: accept-proxy`, I think

**Comment by yunspace** [comment]
Thanks @tifayuki will try it out

**Comment by yunspace** [comment]
The setting suggested by @tifayuki works, please close this PR

**Comment by nclaw** [comment]
Thanks @tifayuki

**Pull request closed without merging**
